#!/usr/bin/env bash

# Helper script to run cargo commands from a Docker environment.
# <SERIAL_PORT> should be the serial port used to flash the ESP32 (e.g. /dev/ttyUSB0)

print_usage() {
  printf "\n%s\nesp-cargo: Run a cargo command with a configured embedded development environment.\n%s\n"
  printf "Usage: esp-cargo [-d SERIAL_PORT] <COMMAND> [ARG...]\n"
}

DEVICE=/dev/ttyUSB0 # default
while getopts ":h:d:" o; do
    case "${o}" in
        h) print_usage; exit ;;
        d) DEVICE=${OPTARG} ;;
       \?) echo "Unknown option -$OPTARG"; print_usage; exit 1;;
    esac
done
shift $((OPTIND-1))

# Must add group (usually dialout) for Docker to have permissions
GROUP=$(stat -c "%G" "${DEVICE}")

docker run -it --init --rm -v .:/esp --group-add "${GROUP}" --device="${DEVICE}" -e ESPFLASH_PORT="${DEVICE}" "$(docker build -q .)" "${@:1}" || print_usage;
